server:
  port: 2002

spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: LeoLee
    password: lyl512240816
    virtual-host: /LeoLee
    listener:
      simple:
        acknowledge-mode: manual #消费者端确认模式:none自动确认 manual手动确认 auto通过抛出异常的类型，来做响应的处理
        concurrency: 1 #当前监听的数量
        max-concurrency: 5 #侦听器调用程序线程的最大数目
        retry:
          enabled: true #是否支持重试
          max-attempts: 4 #最大重试次数，默认为3
        prefetch: 2 #消费端限流5 每个消费者未确认的未处理消息的最大数量
      direct:
        acknowledge-mode: manual    #acknowledgeMode设置为手动模式
