server:
  port: 2001

spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: LeoLee
    password: lyl512240816
    virtual-host: /LeoLee
    publisher-confirms: true #开启confirm确认模式
    publisher-returns: true #开启return回退模式
